// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SavePlayerData(string key, string value)
        {
            await k_Service.CallModuleEndpointAsync(
                "ARaccountCloud",
                "SavePlayerData",
                new Dictionary<string, object>()
                {
                    {"key", key},
                    {"value", value},
                });
        }

        public async Task<string> GetPlayerData(string key)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "ARaccountCloud",
                "GetPlayerData",
                new Dictionary<string, object>()
                {
                    {"key", key},
                });
        }

        public async Task<string> HandleNewPlayerNameEntry(string newName)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "ARaccountCloud",
                "HandleNewPlayerNameEntry",
                new Dictionary<string, object>()
                {
                    {"newName", newName},
                });
        }
    }
}
